=== HRtec-Sp-z-o-o/active-directory-configuration-manager/assets/configuration-element.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           targetNamespace="http://www.magiumlib.com/Configuration" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="configuration">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="section" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="group" maxOccurs="unbounded" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="element" maxOccurs="unbounded" minOccurs="1">
                                            <xs:complexType mixed="true">
                                                <xs:sequence>
                                                    <xs:element type="xs:string" name="description" minOccurs="0" />
                                                    <xs:element type="xs:string" name="value" minOccurs="0">
                                                        <xs:complexType mixed="true">
                                                            <xs:attribute type="xs:string" name="callbackToStorage"
                                                                          use="optional"/>
                                                            <xs:attribute type="xs:string" name="callbackFromStorage"
                                                                          use="optional"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute type="xs:string" name="id" use="required"/>
                                                <xs:attribute type="xs:string" name="name" use="optional"/>
                                                <xs:attribute type="xs:string" name="source" use="optional"/>
                                                <xs:attribute type="xs:string" name="type" use="optional"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="id" use="required"/>
                                    <xs:attribute type="xs:string" name="name" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="id" use="required"/>
                        <xs:attribute type="xs:string" name="name" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== HRtec-Sp-z-o-o/active-directory-configuration-manager/tests/Adapter/xml/config.xml
<?xml version="1.0" encoding="utf-8"?>
<configuration xmlns="http://www.magiumlib.com/Configuration"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.magiumlib.com/Configuration ../../../assets/configuration-element.xsd">
    <section id="general" name="General">
        <group id="website" name="Website">
            <element id="title" name="Title">
                <value>My Homepage</value>
            </element>
            <element id="languages" name="Languages" source="Namespace\MySource" type="multi"/>
        </group>
        <group id="design" name="Design">
            <element id="theme" name="Theme"/>
        </group>
    </section>
    <section id="security" name="Security">
        <group id="authentication" name="Authentication">
            <element id="require" name="Require Authentication" type="select" source="Magium\Configuration\Source\YesNo"/>
        </group>
    </section>
</configuration>
